// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package products_sql

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID          int32         `json:"id"`
	OwnerID     int32         `json:"ownerId"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       int32         `json:"price"`
	ProductType string        `json:"productType"`
	CreatedAt   time.Time     `json:"createdAt"`
	MediaID     uuid.NullUUID `json:"mediaId"`
}

type ProductType struct {
	ID       int32  `json:"id"`
	TypeName string `json:"typeName"`
}
