// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package products_sql

import (
	"time"
)

type Product struct {
	ID          int32     `json:"id"`
	OwnerID     int32     `json:"ownerId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       int32     `json:"price"`
	CreatedAt   time.Time `json:"createdAt"`
}
