name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - name: cd into directory
        run: cd project
      - name: Build the stack
        run: make up_infra
