name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - name: cd into directory
        run: cd project && make up_build_all_d
      - name: add to web network
        run: docker network connect web project-nginx-1
